años_experiencia = input("Ingrese los años de experiencia laboral que ha obtenido =>")
cargo = input("Ingresa el último cargo que has ocupado en tu experiencia laboral => ")
titulo = input("Ingresa el título académico o profesional más relevante para su campo laboral => ")
experiencia_laboral = tuple((años_experiencia, cargo, titulo))
print (experiencia_laboral)